Payment requests
GreenMeteor/verified pull request #25
Opened 2023-05-27 06:07 UTC by ArchBlood

Resolves #21

2023-05-27 13:29 UTC, felixhahnweilheim reviewed
It seems the controller for the options page is missing.

And I would display the account menu item only if Paypal has been configured by the admin.

2023-05-27 19:29 UTC, felixhahnweilheim commented
> It seems the controller for the options page is missing.

Ah no, the controller action is there but called "actionRequest". That's why I got "Page not found". Renaming it to "actionOptions" solved the issue. It would be good to also rename the RequestBadge model class to Options or similar.

2023-05-27 20:09 UTC, ArchBlood commented on views/admin/index.php
> +<div class="container">
No, `container` provides equality for all HTML container elements, so that it leaves no blank spacings.

### With `container`
![Screenshot_1](https://github.com/GreenMeteor/verified/assets/35392110/728564c4-a6da-4062-9dfd-4a0f762f7095)

### Without `container`
![Screenshot_2](https://github.com/GreenMeteor/verified/assets/35392110/673c68c8-5870-4063-8127-a56510d2d60e)

2023-05-27 20:44 UTC, felixhahnweilheim requested changes
Remaining points:
- [ ] controller action for the payment/request form is now missing (but the admin option page works now)
- [x] I still do not agree with the div `container`, see my screenshot. The button on the right is not visible on my laptop!
- [x] the icon in the account menu
- [x] hide the account menu item if PayPal is not set up (i.e. the PayPal ID is empty). I thnk there are communities that won't use the payment form at all.

2023-05-27 20:44 UTC, felixhahnweilheim commented on views/admin/index.php
> +<div class="container">
Yes, but it adds a fix width of 1170px which doesn't work on smaller screen, see screenshot.

div class="container" is already present on the page (around sidebar and content). I think we should do it like all the other settings pages (even if it is not perfect for large screens).

![Screenshot 2023-05-27 at 22-11-18 Administration - Felix Hahn Development](https://github.com/GreenMeteor/verified/assets/84990763/bdb47c84-30d6-4070-b6e2-f24e90511c70)

2023-05-27 20:44 UTC, felixhahnweilheim commented on views/admin/index.php
> +<div class="container">
The actual problem is that div container (wrapping sidebar and content) is just 1170px wide. But this is a core theme problem not an issue of this module.

2023-05-27 20:44 UTC, felixhahnweilheim commented on Events.php
> +            'isActive' => (Yii::$app->controller->module && Yii::$app->controller->module->id === 'verified' || Yii::$app->controller->id === 'index')
I think this line can be removed as it is a modal window.

2023-05-27 21:04 UTC, felixhahnweilheim commented
For my testing: How do I get the plan ID? I have never set up a PayPal plan before. (I only have the Client ID so far.)

Strangely the PayPal buttons don't show up when I click the menu item the first time, but the second time they show up.  

Then when I click a button a window tries to open but closes again (probably because the Plan ID is wrong ... ?)

2023-05-27 21:34 UTC, felixhahnweilheim commented
Ok, I found how to add a subscription plan and have entered the Plan ID.
The PayPal window still closes right after it opened.
When I copy/paste the exact code PayPal suggested, it seems to work (clicking the second time). (I did not test a full payment so far but the PayPal window opens and asks to log in.)

That's the code PayPal suggested to me (not sure what the relevant difference is):

```
<div id="paypal-button-container-MY_PLAN_ID"></div>
<script src="https://www.paypal.com/sdk/js?client-id=MY_PAYPAL_ID&vault=true&intent=subscription" data-sdk-integration-source="button-factory"></script>
<script>
  paypal.Buttons({
      style: {
          shape: 'rect',
          color: 'gold',
          layout: 'vertical',
          label: 'subscribe'
      },
      createSubscription: function(data, actions) {
        return actions.subscription.create({
          /* Creates the subscription */
          plan_id: 'MY_PLAN_ID'
        });
      },
      onApprove: function(data, actions) {
        alert(data.subscriptionID); // You can add optional success message for the subscriber here
      }
  }).render('#paypal-button-container-MY_PLAN_ID'); // Renders the PayPal button
</script>
```

2023-05-27 22:01 UTC, ArchBlood commented on views/admin/index.php
> +<div class="container">
> The actual problem is that div container (wrapping sidebar and content) is just 1170px wide. But this is a core theme problem not an issue of this module.

Then I believe we should report this to HumHub, I can definitely see the issue, so I believe we can keep the current `container` here for now and then ask for the core changes to be done for v1.15 as I believe this is of importance for theme and module development . :thinking:

2023-05-27 22:02 UTC, ArchBlood commented on views/admin/index.php
> +<div class="container">
The other option would be using `container-fluid` here, which looks a lot better.

2023-05-28 01:37 UTC, ArchBlood commented
> Ok, I found how to add a subscription plan and have entered the Plan ID. The PayPal window still closes right after it opened. When I copy/paste the exact code PayPal suggested, it seems to work (clicking the second time). (I did not test a full payment so far but the PayPal window opens and asks to log in.)
> 
> That's the code PayPal suggested to me (not sure what the relevant difference is):
> 
> ```
> <div id="paypal-button-container-MY_PLAN_ID"></div>
> <script src="https://www.paypal.com/sdk/js?client-id=MY_PAYPAL_ID&vault=true&intent=subscription" data-sdk-integration-source="button-factory"></script>
> <script>
>   paypal.Buttons({
>       style: {
>           shape: 'rect',
>           color: 'gold',
>           layout: 'vertical',
>           label: 'subscribe'
>       },
>       createSubscription: function(data, actions) {
>         return actions.subscription.create({
>           /* Creates the subscription */
>           plan_id: 'MY_PLAN_ID'
>         });
>       },
>       onApprove: function(data, actions) {
>         alert(data.subscriptionID); // You can add optional success message for the subscriber here
>       }
>   }).render('#paypal-button-container-MY_PLAN_ID'); // Renders the PayPal button
> </script>
> ```

The current code is fine, the main issue is there is no `unload` function for PJAX, and you can't disable PJAX in `MenuLink` class. :thinking:
If you load the page then open, the subscribe buttons won't show till you close then open again.

2023-05-28 20:39 UTC, felixhahnweilheim commented on views/admin/index.php
> +<div class="container">
I don't see a difference between using `container-fluid` and completely removing the div.

All the other settings pages simply start with `<div class="panel panel-default">`. So I think we should do it the same. It is important that the button on the right is visible on every screen. (More important than a wide layout for large screens.)

By the way, the clean theme has a better layout for large screens (without the need of the `container`)

2023-05-28 21:16 UTC, felixhahnweilheim commented
You are right, the PayPal code is correct. I can't really help with PJAX but would it work in a normal page instead of a modal window?

2023-05-29 00:34 UTC, ArchBlood commented
> You are right, the PayPal code is correct. I can't really help with PJAX but would it work in a normal page instead of a modal window?

Sadly no, as pjax is still applied for single page loads, and all HumHub native menu classes don't support `data-pjax => 0` in `htmlOptions` so we can't really disable it in this way, the only way to fix this issue is to do something like what's done in both the scroll up and weather modules.

2023-05-29 00:37 UTC, ArchBlood commented
@luke- is there a better way of doing this? As of now we can't change or modify the JavaScript code from PayPal to comply with HumHub's JavaScript methods or pjax in general. :thinking:

2023-05-29 00:46 UTC, ArchBlood commented
> Remaining points:
> - [ ] controller action for the payment/request form is now missing (but the admin option page works now)

Could you provide more information for this? I'm not currently seeing issues with controller actions

> - [ ] hide the account menu item if PayPal is not set up (i.e. the PayPal ID is empty). I thnk there are communities that won't use the payment form at all.

I'll add a `checkbox()` option for this as soon as I'm back at the work desk.

2023-05-29 06:26 UTC, felixhahnweilheim commented
I get "The required ressource was not found" when clicking "Verification Request" in the account menu.


I don't think we really need a checkbox. We could also add a hint in the options page "Leave this empty to hide the payment form". But do it as you prefer.

2023-05-29 06:45 UTC, ArchBlood commented
> I get "The required ressource was not found" when clicking "Verification Request" in the account menu.

I'll look into this. Could you provide any logging if they appear?

> I don't think we really need a checkbox. We could also add a hint in the options page "Leave this empty to hide the payment form". But do it as you prefer.

Currently the fields are set to `required` so they can't be left blank, I'd prefer the `checkbox()` option which will enable or disable the function and hide the account menu link.

2023-05-29 07:14 UTC, felixhahnweilheim commented
The whole error message:

```
{ "url": "/verified/payment/index", "status": 404, "response": { "error": true, "message": "Seite nicht gefunden." }, "textStatus": "error", "xhr": { "readyState": 4, "responseText": "{\"error\":true,\"message\":\"Seite nicht gefunden.\"}", "responseJSON": { "error": true, "message": "Seite nicht gefunden." }, "status": 404, "statusText": "Not Found" }, "dataType": "json", "error": true, "message": "Seite nicht gefunden.", "errorThrown": "Not Found", "validationError": false }
```

2023-05-29 07:59 UTC, ArchBlood commented
> The whole error message:
> 
> ```
> { "url": "/verified/payment/index", "status": 404, "response": { "error": true, "message": "Seite nicht gefunden." }, "textStatus": "error", "xhr": { "readyState": 4, "responseText": "{\"error\":true,\"message\":\"Seite nicht gefunden.\"}", "responseJSON": { "error": true, "message": "Seite nicht gefunden." }, "status": 404, "statusText": "Not Found" }, "dataType": "json", "error": true, "message": "Seite nicht gefunden.", "errorThrown": "Not Found", "validationError": false }
> ```

Are you using a git pull method when updating the code or manually updating?

2023-05-29 08:26 UTC, felixhahnweilheim commented
I pulled the payment branch (using the git extension of Plesk).

2023-05-29 08:28 UTC, felixhahnweilheim commented
The checkbox is good. I would just call it "Enable".

2023-05-29 08:49 UTC, ArchBlood commented on views/admin/index.php
> +<div class="container">
Okay, so after working with `container-fluid`/`container` and no `container` where's the results for the default theme;

### With `container-fluid`
![Screenshot_1](https://github.com/GreenMeteor/verified/assets/35392110/a52cb746-6819-41e7-8e92-4e6a8bca0397)

### With `container`
![Screenshot_3](https://github.com/GreenMeteor/verified/assets/35392110/2948b5c8-7f41-43f9-b48e-990a3d4a1126)


### Without `container-fluid` or `container`
![Screenshot_2](https://github.com/GreenMeteor/verified/assets/35392110/32de6073-ecc0-4c86-ad57-15a8d1b3f5ca)

Looking at the `theme.css` I see the following which seems to be the issue?
```css
.col-md-1,.col-md-2,.col-md-3,.col-md-4,.col-md-5,.col-md-6,.col-md-7,.col-md-8,.col-md-9,.col-md-10,.col-md-11,.col-md-12{
    position:inherit
}
```
Which I can definitely say is a bug in the default theme design @luke-.

2023-05-29 09:26 UTC, ArchBlood commented on views/admin/index.php
> +<div class="container">
Suggestion would be to remove padding from `.container` as it's not needed at all in the container, the theme.css should handle this by default.

Another suggestion would be the following be changed as well
```css
.container-fluid{
    padding-right: 15px;
    padding-left: 15px;
    margin-right: auto; /* Actually does nothing at all */
    margin-left: auto; /* Also does nothing */
}
```

2023-05-29 09:41 UTC, ArchBlood commented
> I pulled the payment branch (using the git extension of Plesk).

Is this before or after clearing cache (i.e `/assets` folder)?

2023-05-29 10:32 UTC, felixhahnweilheim commented
> > I pulled the payment branch (using the git extension of Plesk).
> 
> Is this before or after clearing cache (i.e `/assets` folder)?

Now I cleared the cache (and the whole assets directory) but nothing changed.

2023-05-29 19:38 UTC, ArchBlood commented
> > > I pulled the payment branch (using the git extension of Plesk).
> > 
> > 
> > Is this before or after clearing cache (i.e `/assets` folder)?
> 
> Now I cleared the cache (and the whole assets directory) but nothing changed.

I am unable to reproduce this currently, maybe this is because of enabled state? Are there any error stacks in **_ACP > Information > Logging_**?

2023-05-29 20:26 UTC, ArchBlood commented on controllers/OptionsController.php
> +        return $this->renderAjax('index', ['model' => $model]);
https://github.com/GreenMeteor/verified/pull/25#pullrequestreview-1447381063

After reviewing and testing the `actionIndex()` renders `helper\Url::getOptionsUrl()` as expected so I'm not able to reproduce missing action for `/verified/payment/index` so there could be another issue, such as not deleting old controller(s), models, views or `helper\Url::{getMissingMethod}`.

2023-05-29 20:49 UTC, felixhahnweilheim commented on controllers/OptionsController.php
> +        return $this->renderAjax('index', ['model' => $model]);
Very strange. I have the error on two different installations. I don't have any old files left, I completely emptied the module directory and pulled again.
But when I rename the OptionsController (file name and class name) to PaymentController everything works.

2023-05-29 21:07 UTC, felixhahnweilheim commented on controllers/OptionsController.php
> +        return $this->renderAjax('index', ['model' => $model]);
By the way, shouldn't we remove the if clause? We don't want to save the (admin) payment options from this form.

2023-05-29 21:14 UTC, felixhahnweilheim commented on Events.php
> +	            'data-action-click-url' => helpers\Url::getOptionsUrl(),
It would be clearer to update the wording "getOptionsUrl". For example "getPaymentUrl", "getVerificationCenterUrl" or "getRequestUrl".

2023-05-29 21:32 UTC, ArchBlood commented on controllers/OptionsController.php
> +        return $this->renderAjax('index', ['model' => $model]);
> By the way, shouldn't we remove the if clause? We don't want to save the (admin) payment options from this form.

Should just need to remove the `saveSettings()` part and it should work as needed.

2023-05-29 21:33 UTC, ArchBlood commented on controllers/OptionsController.php
> +        return $this->renderAjax('index', ['model' => $model]);
> But when I rename the OptionsController (file name and class name) to PaymentController everything works.

We'll go with that then.

2023-05-29 21:39 UTC, felixhahnweilheim commented on controllers/OptionsController.php
> +        return $this->renderAjax('index', ['model' => $model]);
> Should just need to remove the `saveSettings()` part and it should work as needed.

I don't understand why we should (try to) load the PaymentOptions() model with POST data here. But if you have a reason I'm ok with it.

2023-05-29 22:23 UTC, ArchBlood commented on controllers/OptionsController.php
> +        return $this->renderAjax('index', ['model' => $model]);
> > Should just need to remove the `saveSettings()` part and it should work as needed.
> 
> I don't understand why we should (try to) load the PaymentOptions() model with POST data here. But if you have a reason I'm ok with it.

We're loading `post()` data from `/verified/payment/index`, without this the modal will instantly close on open of the modal.

2023-05-29 22:27 UTC, ArchBlood commented on Events.php
> +	            'data-action-click-url' => helpers\Url::getOptionsUrl(),
As much as I like `getPaymentUrl` I believe `getOptionsUrl` fits better as you're loading payment options here. :thinking:

2023-05-29 22:43 UTC, ArchBlood commented on controllers/OptionsController.php
> +        return $this->renderAjax('index', ['model' => $model]);
In light of https://www.yiiframework.com/doc/api/2.0/yii-web-request#post()-detail we should keep `$model->saveSettings()` so we don't array all `POST` parameters.

2023-05-29 23:48 UTC, ArchBlood commented
I'm rather happy with the P/R currently, other than the PJAX issues. 🤔

2023-05-30 06:38 UTC, felixhahnweilheim commented on Events.php
> +	            'data-action-click-url' => helpers\Url::getOptionsUrl(),
Ok, I see, makes sense.

2023-05-30 07:08 UTC, felixhahnweilheim commented on controllers/OptionsController.php
> +        return $this->renderAjax('index', ['model' => $model]);
Actually it works with just `return $this->renderAjax('index');`

We don't have to pass any data to the view because it catches the data directly from the module settings.

2023-05-31 11:41 UTC, ArchBlood commented
Everything is ready for testing!

I ended up finding a slight hackish way of implementing the JavaScript which works wonderfully with no errors showing for me in the browser console, I also found a way of disabling pjax with `['options' => [data-pjax => 0]]` in the `ActiveForm::begin()` tag so that the inline script actually works on the div `id`.

2023-05-31 13:52 UTC, felixhahnweilheim approved these changes
Great. Now I am happy with the PR.

2023-05-31 14:14 UTC, merged